wheel_radius: 0.037230282
half_wheelbase: 0.106000002
half_track: 0.125000000
roller_layout: X
wheel_signs: [1.0, 1.0, 1.0, 1.0]
max_wheel_speed: 30.0
cmd_timeout: 0.5
publish_rate: 50.0
cmd_vel_topic: /cmd_vel
wheel_command_topic: /wheel_velocity_controller/command
odom_topic: /wheel/odom
