# =========================================================
# Frames
# =========================================================

global_frame_id: map
odom_frame_id: odom
base_frame_id: base_footprint

tf_broadcast: true
transform_tolerance: 0.5


# =========================================================
# Particle Filter
# =========================================================

min_particles: 300
max_particles: 2000

kld_err: 0.02
kld_z: 0.99

resample_interval: 1

update_min_d: 0.02
update_min_a: 0.03

recovery_alpha_slow: 0.0
recovery_alpha_fast: 0.0


# =========================================================
# Laser model
# =========================================================

laser_model_type: likelihood_field

laser_max_beams: 60

laser_min_range: 0.10
laser_max_range: 8.0

laser_z_hit: 0.95
laser_z_rand: 0.05

laser_sigma_hit: 0.20
laser_likelihood_max_dist: 2.0


# =========================================================
# Odometry model
# Mecanum / holonomic robot
# =========================================================

odom_model_type: omni-corrected

odom_alpha1: 0.10
odom_alpha2: 0.10
odom_alpha3: 0.10
odom_alpha4: 0.10
odom_alpha5: 0.10


# =========================================================
# Publish
# =========================================================

gui_publish_rate: 10.0
save_pose_rate: 0.5
